spring:
  datasource:
    url: jdbc:mysql:///library
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        fromat_sql: true

server:
  port: 8081
